import { createFileRoute, Link } from "@tanstack/react-router";
import { Backdrop } from "@/components/wf/Backdrop";
import { Brand } from "@/components/wf/Brand";
import { GhostButton } from "@/components/wf/ui";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — WonderFlow OS" },
      { name: "description", content: "The terms that govern use of WonderFlow OS." },
    ],
  }),
  component: TermsOfService,
});

const LAST_UPDATED = "September 19, 2026";

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="mt-10 text-xl font-semibold text-foreground" style={{ fontFamily: "var(--font-display)" }}>{children}</h2>;
}
function P({ children }: { children: React.ReactNode }) {
  return <p className="mt-3 text-sm leading-relaxed text-muted-foreground">{children}</p>;
}
function Ul({ children }: { children: React.ReactNode }) {
  return <ul className="mt-3 list-disc space-y-1.5 pl-5 text-sm leading-relaxed text-muted-foreground">{children}</ul>;
}

function TermsOfService() {
  return (
    <main className="relative min-h-screen">
      <Backdrop intensity={0.5} />
      <header className="mx-auto flex w-full max-w-3xl items-center justify-between px-6 py-7">
        <Link to="/"><Brand /></Link>
        <Link to="/"><GhostButton className="px-5 py-2.5">Back</GhostButton></Link>
      </header>

      <div className="mx-auto w-full max-w-3xl px-6 pb-24">
        <p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Legal</p>
        <h1 className="mt-2 text-3xl tracking-tight sm:text-4xl" style={{ fontFamily: "var(--font-display)" }}>
          <span className="gold-text italic">Terms of Service</span>
        </h1>
        <p className="mt-3 text-xs text-muted-foreground">Last updated {LAST_UPDATED}</p>

        <H2>1. Acceptance of terms</H2>
        <P>By creating a WonderFlow account or using the service, you agree to these terms. If you're using WonderFlow on behalf of a business, you're confirming you have authority to bind that business to these terms.</P>

        <H2>2. The service</H2>
        <P>
          WonderFlow OS is a business operating system — CRM, orders, inventory, finance, automation, analytics, and related
          tools — offered as a hosted (SaaS) product. Features vary by plan; some rely on third-party services (Stripe for payments,
          Anthropic for AI features, Resend for email, and optional integrations like Slack, Meta, or TikTok) that carry their own
          terms and availability.
        </P>

        <H2>3. Accounts</H2>
        <P>
          You're responsible for the accuracy of the information you provide and for keeping your login credentials secure. You're
          responsible for activity that happens under your account, including actions taken by team members you invite. We offer
          optional two-factor authentication — we recommend enabling it.
        </P>

        <H2>4. Plans &amp; billing</H2>
        <P>
          Paid plans are billed through Stripe on the cycle shown at checkout. You can change or cancel your plan at any time from
          Billing in the app; changes take effect per Stripe's standard proration rules. Fees are non-refundable except where
          required by law.
        </P>

        <H2>5. Your data &amp; content</H2>
        <P>
          You own the business data you put into WonderFlow — customers, orders, content, and everything else. We process it only to
          provide the service to you, as described in our <Link to="/privacy" className="text-gold hover:underline">Privacy Policy</Link>.
          You're responsible for having the right to use and store the data you enter, including your own customers' information.
        </P>

        <H2>6. AI features</H2>
        <P>
          WonderFlow's AI features are generated by a large language model and can be inaccurate, incomplete, or inappropriate for
          your specific situation — review AI-drafted content (emails, automations, advice) before relying on it or sending it to
          customers. AI outputs are provided "as is," without a guarantee of accuracy.
        </P>

        <H2>7. Third-party integrations</H2>
        <P>
          If you connect a third-party service (Stripe, Slack, Meta/Instagram/Facebook, TikTok, or an outbound webhook to Zapier,
          Make, or n8n), you're responsible for complying with that service's own terms of use. WonderFlow isn't responsible for the
          availability, accuracy, or behavior of third-party services, including changes they make that affect functionality.
        </P>

        <H2>8. Acceptable use</H2>
        <P>You agree not to:</P>
        <Ul>
          <li>Use WonderFlow for anything unlawful, fraudulent, or that infringes someone else's rights.</li>
          <li>Attempt to bypass security measures, access another workspace's data, or disrupt the service.</li>
          <li>Use WonderFlow to send spam or unsolicited communications that violate applicable law.</li>
          <li>Reverse-engineer or resell the service without our written permission.</li>
        </Ul>

        <H2>9. Termination</H2>
        <P>
          You can delete your account or close a business you own at any time from Settings. We may suspend or terminate accounts
          that violate these terms, with notice where practical. On termination, your right to use the service ends; some data may
          be retained as described in our Privacy Policy.
        </P>

        <H2>10. Disclaimers &amp; limitation of liability</H2>
        <P>
          WonderFlow is provided "as is" without warranties of any kind, to the extent permitted by law. We're not liable for
          indirect, incidental, or consequential damages arising from your use of the service, including decisions made based on
          AI-generated content or business data processed through the platform.
        </P>

        <H2>11. Changes to these terms</H2>
        <P>We'll update the "Last updated" date above when these terms change, and post material changes here.</P>

        <H2>12. Governing law</H2>
        <P><span className="text-foreground/80">[Add your business's governing jurisdiction here.]</span></P>

        <H2>13. Contact</H2>
        <P>
          Questions about these terms can be sent through the Suggestions &amp; Reviews panel in the app, or to{" "}
          <span className="text-foreground/80">[add your support/legal contact email here]</span>.
        </P>

        <p className="mt-10 rounded-2xl border border-gold/25 bg-glass px-4 py-3 text-xs text-muted-foreground">
          This is a working draft, useful as a real starting point (including for third-party app reviews like Meta's), but it
          hasn't been reviewed by a lawyer. Have it checked before relying on it for legal compliance, and fill in the governing
          jurisdiction and contact details above.
        </p>
      </div>
    </main>
  );
}
