/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as TeamRouteImport } from './routes/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/growth': typeof GrowthRoute
  '/inventory': typeof InventoryRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/score': typeof ScoreRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/growth': typeof GrowthRoute
  '/inventory': typeof InventoryRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/score': typeof ScoreRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/growth': typeof GrowthRoute
  '/inventory': typeof InventoryRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/score': typeof ScoreRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advisor'
    | '/analytics'
    | '/auth'
    | '/automation'
    | '/crm'
    | '/dashboard'
    | '/growth'
    | '/inventory'
    | '/onboarding'
    | '/orders'
    | '/score'
    | '/suppliers'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advisor'
    | '/analytics'
    | '/auth'
    | '/automation'
    | '/crm'
    | '/dashboard'
    | '/growth'
    | '/inventory'
    | '/onboarding'
    | '/orders'
    | '/score'
    | '/suppliers'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advisor'
    | '/analytics'
    | '/auth'
    | '/automation'
    | '/crm'
    | '/dashboard'
    | '/growth'
    | '/inventory'
    | '/onboarding'
    | '/orders'
    | '/score'
    | '/suppliers'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdvisorRoute: typeof AdvisorRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  AutomationRoute: typeof AutomationRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  GrowthRoute: typeof GrowthRoute
  InventoryRoute: typeof InventoryRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  ScoreRoute: typeof ScoreRoute
  SuppliersRoute: typeof SuppliersRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdvisorRoute: AdvisorRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  AutomationRoute: AutomationRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  GrowthRoute: GrowthRoute,
  InventoryRoute: InventoryRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  ScoreRoute: ScoreRoute,
  SuppliersRoute: SuppliersRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
